export type Page = { slug: string; title: string; category: string; group: string; summary: string; intro: string; sections: { heading: string; body: string; points?: string[] }[]; comparison?: { criterion: string; local: string; global: string }[]; faq?: { question: string; answer: string }[]; sources?: { label: string; url: string; note: string }[]; relatedTemplate?: string; template?: { content:string; instructions:string; relatedGuide:string } };
import { depth } from "./depth";
import templates from "../data/templates.json";

const core = (title: string, focus: string, audience: string, risks: string[]): Page["sections"] => [
  { heading: `About ${title}`, body: `${focus} This page explains the operating choices that distinguish the format from adjacent community models.` },
  { heading: `Operating decisions for ${title}`, body: `Define the eligible ${audience}, the decision or relationship the format supports, the information that must remain private and the person accountable for quality.`, points: ["State the participant profile", "Name the recurring member value", "Set admission and removal criteria", "Choose a sustainable cadence", "Document sponsor and confidentiality boundaries"] },
  { heading: "Operating procedure", body: "Select participants against written criteria, brief everyone before the session, facilitate contribution, obtain consent for follow-up and review what should continue, change or stop." },
  { heading: "Topic-specific risks", body: `These risks should be addressed before publishing or promoting ${title}.`, points: risks },
  { heading: "Decision check", body: `Confirm that the format, membership criteria and host responsibilities are specific enough for a prospective participant to decide whether ${title} is relevant.` },
];

const specs: Array<[string,string,string,string,string,string,string[]]> = [
  ["how-to-build-an-executive-community","How to Build an Executive Community","Pillar guide","Start here","A practical operating system for moving from audience definition to durable member value.","An executive community is a structured network of senior leaders connected by a relevant shared identity and recurring opportunities to exchange useful knowledge and relationships.", ["Starting with events instead of a member need","Accepting everyone and weakening relevance","Treating attendance as the only success measure"]],
  ["how-to-start-a-ceo-peer-group","How to Start a CEO Peer Group","Pillar guide","Start here","Build a confidential, well-matched peer group with clear standards and a useful cadence.","A CEO peer group is a recurring, facilitated group in which chief executives examine decisions, challenges and leadership responsibilities with peers.",["Mixing incompatible company stages","Allowing sales pitches","Weak facilitation of sensitive discussions"]],
  ["how-to-build-a-global-executive-network","How to Build a Global Executive Network","Global guide","Global networks","Connect senior leaders across markets while preserving regional relevance and trust.","A global executive network connects senior leaders across multiple markets through a shared identity, clear membership standards and recurring opportunities to build trusted professional relationships.",["Becoming a loose mailing list","Forcing identical local formats","Ignoring time zones, culture or privacy rules"]],
  ["private-executive-dinner-playbook","Private Executive Dinner Playbook","Pillar guide","Event formats","Plan a focused dinner that creates candid exchange without pitching or performative networking.","A private executive dinner is a deliberately small, hosted conversation for a defined senior audience, usually organized around one relevant question.",["Overfilled guest lists","Sponsor-led selling","No preparation or follow-up"]],
  ["about-the-project","About the Project","Project","Project","Purpose, publisher and scope of the open reference guide.","The Executive Community Playbook is an open reference guide published by Open Future Forum and Murray Newlands.",["Confusing publisher experience with neutral research","Hiding commercial relationships","Overstating authority"]],
  ["methodology","Methodology","Project","Project","How the playbook develops, reviews and updates practical guidance.","The methodology combines operating experience, editorial analysis, public sources and clearly identified publisher judgment.",["Unsupported universal claims","Unclear sourcing","Stale guidance"]],
  ["publisher-disclosure","Publisher Disclosure","Project","Project","A transparent account of ownership, funding and editorial perspective.","Open Future Forum and Murray Newlands own, fund, publish and edit this project.",["Hidden conflicts","False neutrality","Unlabeled promotion"]],
  ["principles-overview","Principles Overview","Principles","Principles","The operating principles that protect relevance, trust and sustained participation.","Community principles translate the member promise into observable decisions and behavior.",["Principles without enforcement","Too many rules","Organizer exceptions"]],
  ["sponsoring-an-executive-community","Sponsoring an Executive Community","Sponsor guide","Governance","Create sponsor value without compromising member trust or editorial independence.","Responsible sponsorship supports member value while setting firm boundaries on access, data, content and selling.",["Selling attendee lists","Giving sponsors unchecked stage time","Hiding paid relationships"]],
  ["executive-community-charter","Executive Community Charter","Governance","Governance","Define purpose, membership, conduct, confidentiality and decision rights.","A community charter is the shared operating agreement between members and organizers.",["Vague expectations","No removal process","Rules that are never referenced"]],
  ["member-selection","Member Selection","Principles","Principles","Select for relevance, contribution and compatibility rather than status alone.","Member selection is the disciplined process of determining who can both benefit from and contribute to a community.",["Logo collecting","Inconsistent exceptions","Unclear conflicts"]],
  ["trust-and-confidentiality","Trust and Confidentiality","Principles","Principles","Set realistic privacy expectations and make responsibility mutual.","Trust is earned through consistent conduct; confidentiality is a defined practice with practical and legal limits.",["Promising absolute secrecy","Surprise recording","Unclear attribution rules"]],
  ["no-hard-pitching","No Hard Pitching","Principles","Principles","Keep member interactions useful by separating participation from solicitation.","A no-hard-pitching rule prohibits unsolicited selling while allowing relevant, consent-based business conversations.",["Rules aimed only at sponsors","Ambiguous follow-up","Failure to address repeat behavior"]],
  ["give-before-you-get","Give Before You Get","Principles","Principles","Build reputation through useful contributions before requesting access or favors.","Give before you get is a participation norm that rewards knowledge, introductions and support rather than extraction.",["Performative generosity","Transactional introductions","Unequal enforcement"]],
  ["signal-over-scale","Signal Over Scale","Principles","Principles","Prioritize audience fit and useful participation at any network size.","Signal over scale means optimizing for relevance and contribution rather than treating raw audience size as proof of value.",["Using the principle to reject growth","Confusing exclusivity with quality","Ignoring network reach"]],
  ["executive-community-vs-ceo-peer-group","Executive Community vs CEO Peer Group","Comparison","Comparisons","Compare audience, structure, depth, facilitation and member commitments.","An executive community is usually broader and offers varied interactions; a CEO peer group is narrower, recurring and oriented toward confidential peer problem solving.",["Treating the labels as interchangeable","Mismatched expectations","Copying one governance model"]],
  ["ceo-peer-group-vs-mastermind","CEO Peer Group vs Mastermind","Comparison","Comparisons","Distinguish executive peer governance from goal-oriented mastermind formats.","CEO peer groups emphasize chief executive decisions and confidentiality; masterminds often center on individual goals and mutual accountability.",["Ambiguous positioning","Mixed seniority","Overpromising outcomes"]],
  ["executive-forum-vs-advisory-board","Executive Forum vs Advisory Board","Comparison","Comparisons","Clarify whether executives are peers, advisers or formal governance participants.","An executive forum serves peer exchange; an advisory board provides structured counsel to an organization without the fiduciary role of a statutory board.",["Misrepresenting governance authority","Unclear compensation","Conflicted advice"]],
  ["membership-community-vs-event-series","Membership Community vs Event Series","Comparison","Comparisons","Decide whether value comes from belonging over time or individual programs.","A membership community offers a continuing identity and relationship system; an event series offers a recurring program without necessarily creating membership obligations.",["Calling an audience a community","No between-event value","Unclear membership"]],
  ["local-executive-community-vs-global-executive-network","Local Executive Community vs Global Executive Network","Comparison","Global networks","Combine local relationship depth with cross-market reach.","Local and global models are not mutually exclusive. A strong global network often builds its deepest relationships through regional gatherings and functional peer groups.",["Expanding before local value is repeatable","Geographic fragmentation","Central control without local context"]],
  ["ceo-communities","CEO Communities","Role guide","Role-based forums","Design for company leadership, isolation, judgment and cross-industry learning.","CEO communities bring chief executives together around decisions that are difficult to discuss inside their own organizations.",["Mixing sellers with peers","Ignoring company stage","Advice without context"]],
  ["cfo-communities","CFO Communities","Role guide","Role-based forums","Serve finance leaders managing capital, risk, performance and transformation.","CFO communities connect senior finance leaders facing capital allocation, reporting, talent, systems and strategic partnership decisions.",["Vendor-heavy agendas","Weak confidentiality","Generic finance content"]],
  ["cmo-communities","CMO Communities","Role guide","Role-based forums","Create relevant exchange on growth, brand, measurement and changing channels.","CMO communities convene marketing leaders around growth, reputation, customer insight, technology and organizational influence.",["Trend-only content","Agency pitching","Ignoring company context"]],
  ["ciso-communities","CISO Communities","Role guide","Role-based forums","Protect sensitive exchange on threats, resilience, governance and leadership.","CISO communities require unusually clear boundaries because useful peer exchange may involve active risks and sensitive operational context.",["Recording sensitive sessions","Vendor dominance","Careless incident discussion"]],
  ["ai-executive-communities","AI Executive Communities","Role guide","Role-based forums","Connect leaders responsible for AI strategy, deployment, governance and value.","AI executive communities serve leaders translating rapidly changing capabilities into responsible organizational decisions.",["Hype-led programming","Undefined seniority","Mixing product demos with peer exchange"]],
  ["private-equity-executive-communities","Private Equity Executive Communities","Role guide","Role-based forums","Convene investors, operating partners and portfolio leaders around value creation.","Private equity executive communities need clear rules for confidential portfolio information, deal conflicts and commercial introductions.",["Deal solicitation","Competitive conflicts","Unclear investor-operator balance"]],
  ["private-executive-dinner","Private Executive Dinner","Format guide","Event formats","A step-by-step operating format for a confidential hosted dinner.","The dinner format uses hospitality and a focused table to create an extended executive conversation.",["Too many presentations","Poor seating design","No host briefing"]],
  ["executive-roundtable","Executive Roundtable","Format guide","Event formats","Facilitate structured contribution around a defined executive question.","An executive roundtable is a moderated discussion in which every participant has a credible opportunity to contribute.",["Panel-style imbalance","Broad topics","Dominant participants"]],
  ["peer-board-meeting","Peer Board Meeting","Format guide","Event formats","Use a disciplined case-review format for consequential member challenges.","A peer board meeting applies a board-like discussion structure to member decisions without creating formal corporate governance authority.",["Confusing advice with authority","Weak case preparation","No follow-through"]],
  ["executive-workshop","Executive Workshop","Format guide","Event formats","Turn peer insight into a concrete plan, artifact or decision.","An executive workshop is a facilitated working session designed to produce an applied outcome, not just discussion.",["Lecture-heavy design","No pre-work","Unclear output"]],
  ["executive-community-measurement","Executive Community Measurement","Measurement","Measurement","Measure trust, relevance, participation and member outcomes without vanity metrics.","Community health is a balanced view of member fit, repeat participation, useful relationships, contributions and realized value.",["Counting registrations alone","Surveying too often","Metrics without decisions"]],
  ["research-from-executive-communities","Research from Executive Communities","Research","Research","Turn first-party executive insight into useful, ethical knowledge products.","Community research can combine surveys, interviews and facilitated discussions when consent, attribution and methodology are clear.",["Publishing private remarks","Biased samples","Sponsor influence on findings"]],
  ["open-future-forum-case-example","Open Future Forum Case Example","Case example","Project","Lessons from a global executive community founded in Silicon Valley in 2019.","Open Future Forum provides one operating example, not a universal model or neutral benchmark.",["Copying without context","Turning the playbook into promotion","Confusing claims with evidence"]],
  ["templates-library","Templates Library","Templates","Templates","Editable starting points for community governance, invitations, events and review.","Templates reduce avoidable ambiguity, but each must be adapted to the audience, format, culture and applicable law.",["Using templates as legal advice","Copying without adaptation","Documents nobody uses"]],
  ["glossary","Glossary","Reference","Reference","Concise definitions for community, peer-group and executive-event terminology.","The glossary gives stable working definitions while acknowledging that organizations use some labels differently.",["Circular definitions","Promotional language","Treating usage as universal"]],
  ["structured-data-page","Structured Data","Reference","Reference","Machine-readable definitions and relationships for reuse and citation.","Structured data mirrors the editorial content with stable identifiers, URLs and last-reviewed dates.",["Conflicting values","Broken identifiers","Stale exports"]],
  ["citation-page","Citation","Project","Project","How to cite, quote and preserve versions of the playbook.","Citations should identify the page title, publisher, version, review date and canonical URL.",["Missing version dates","Deep links without titles","Unlabeled adaptations"]],
  ["contribution-page","Contribution Guide","Project","Project","Propose corrections and improvements while preserving editorial standards.","Contributions are reviewed for practical usefulness, evidence quality, disclosure and fit with the project scope.",["Invented examples","Undisclosed promotion","Unsupported claims"]],
  ["regional-hosts-and-local-conveners","Regional Hosts and Local Conveners","Global operations","Global networks","Set local authority, responsibilities and feedback loops inside a global network.","Regional hosts translate shared standards into locally relevant gatherings and relationships.",["Ambiguous decision rights","Untrained hosts","No quality feedback"]],
  ["cross-border-introductions","Cross-Border Introductions","Global operations","Global networks","Make relevant introductions with consent, context and responsible data handling.","A cross-border introduction connects qualified members in different markets for a stated professional reason.",["Sharing data without consent","Low-context introductions","Ignoring conflicts"]],
];

export const pages: Page[] = specs.map(([slug,title,category,group,summary,intro,risks]) => ({ slug,title,category,group,summary,intro,sections:core(title,intro, group.toLowerCase(),risks) }));

const globalGuide = pages.find(page => page.slug === "how-to-build-a-global-executive-network")!;
globalGuide.sections = [
  { heading: "Local community and global network are different operating systems", body: "A local community concentrates members, context and activity in one market. A global network coordinates identity, standards and relationship opportunities across markets. The global model needs a common member promise, a reliable way to route people toward relevant regional and functional groups, and enough shared activity for members to feel part of one network.", points: ["Global identity with specific membership criteria", "Regional gatherings with local relevance", "Cross-market introductions based on a stated need", "Shared research and content that connect markets", "Consistent trust standards across every format"] },
  { heading: "Define the global member profile", body: "Define eligibility in terms that travel across markets. Job titles, company stages and ownership structures vary by country, so use decision authority, scope, professional relevance and capacity to contribute as primary tests. Publish exceptions and conflict rules so regional growth does not weaken the promise.", points: ["Decision-making scope", "Functional or cross-functional relevance", "Company scale and stage where material", "Market representation goals", "Conflicts, vendors and service-provider rules", "Expected contribution and conduct"] },
  { heading: "Design the regional architecture", body: "Choose where authority sits. A central team can own identity, data standards and member policy while regional conveners own relationships, programming and local partnerships. Define which decisions require approval and which can be adapted locally.", points: ["Assign a named regional host", "Set minimum host and facilitation standards", "Create a local feedback channel", "Review member fit consistently", "Allow format and timing to reflect local norms"] },
  { heading: "Use private gatherings to support wider reach", body: "A global network does not require every event to be global. A private dinner in one city can strengthen a worldwide network when members share an identity, follow common standards and can access cross-market relationships, research or role-based groups. Intimacy is a format choice, not a limit on network reach." },
  { heading: "Combine in-person, digital and hybrid formats", body: "Use each channel for what it does well. In-person gatherings support depth. Digital briefings and peer groups maintain continuity. Asynchronous notes and research connect members who cannot attend. Hybrid meetings should be used selectively because remote participants often receive an inferior experience.", points: ["Regional dinners and roundtables", "Role-based digital peer groups", "Global research briefings", "Member requests and introductions", "Asynchronous regional insight summaries"] },
  { heading: "Manage time zones and cadence", body: "Do not center every global interaction on one headquarters. Rotate live session times, publish the full schedule early, offer regional repetitions where useful and distinguish synchronous programs from materials members can use on demand. Track who is persistently excluded by the calendar." },
  { heading: "Adapt to culture without lowering standards", body: "Participation norms, hierarchy, directness, hospitality and attitudes toward public visibility differ across markets. Regional hosts should adapt facilitation and communication while preserving shared rules for member fit, confidentiality, consent, sponsorship and respectful conduct." },
  { heading: "Handle cross-border introductions responsibly", body: "Make introductions only with a relevant reason and consent from both parties. Share the minimum context needed. Record professional preferences rather than sensitive personal details. When data or communications cross jurisdictions, obtain qualified privacy and legal guidance.", points: ["Confirm the purpose", "Ask both members for consent", "State why the match is relevant", "Avoid forwarding private records", "Provide a graceful way to decline", "Review retention and deletion practices"] },
  { heading: "Select regional partners and sponsors", body: "Choose partners for audience credibility, operating reliability and alignment with member value. A partner should not gain automatic access to members or influence over editorial findings. Define data, invitation, branding, speaking and follow-up rights in writing." },
  { heading: "Measure global reach and local value", body: "Separate network reach from active participation. Review participation by market, repeat attendance, cross-market introductions, member contribution, regional retention and realized outcomes. Compare regions carefully because cadence, maturity and format will differ." },
  { heading: "Prevent geographic fragmentation", body: "Fragmentation begins when chapters operate as unrelated brands or members cannot access value beyond their city. Use shared onboarding, host training, research, member standards and cross-market programming to create connective tissue without forcing every region into the same calendar." },
  { heading: "Launch and expansion checklist", body: "Expand only after the member promise and operating cadence work in the first market.", points: ["Validate demand with qualified leaders in the target region", "Appoint and train a credible local convener", "Map cultural, privacy and event requirements", "Define central and regional decision rights", "Run a small pilot with explicit feedback", "Connect the pilot to wider research or introductions", "Review member fit and sponsor behavior", "Scale only when local participation is repeatable"] },
];
globalGuide.faq = [
  { question: "Does a global executive network need global events?", answer: "No. Regional events can be part of a globally connected network when members share an identity, standards and access to cross-market value." },
  { question: "When should a community expand into another market?", answer: "Expand after the core member promise, admission criteria, hosting method and cadence are repeatable, and after qualified leaders in the new market validate local demand." },
  { question: "Should every regional chapter use the same format?", answer: "No. Standards should be consistent, but formats should adapt to local business culture, member needs, scheduling and venue norms." },
  { question: "How do global networks avoid becoming mailing lists?", answer: "Create recurring member-to-member value through regional gatherings, peer groups, relevant introductions, shared research and clear participation expectations." },
];

const comparisonPage = pages.find(page => page.slug === "local-executive-community-vs-global-executive-network")!;
comparisonPage.comparison = [
  { criterion: "Geographic reach", local: "One city or region", global: "Multiple markets connected by one identity" },
  { criterion: "Relationship depth", local: "Frequent in-person contact can deepen ties", global: "Depth varies and is often built in regional or role groups" },
  { criterion: "Member diversity", local: "Shared market context", global: "Wider sector, culture and market perspectives" },
  { criterion: "Event logistics", local: "Simpler travel and scheduling", global: "Travel, time zones and multiple calendars" },
  { criterion: "Cultural complexity", local: "Fewer variations to manage", global: "Communication and participation norms differ" },
  { criterion: "Sponsorship", local: "Regional budgets and relationships", global: "Central agreements plus regional relevance" },
  { criterion: "Introductions", local: "Proximity supports repeat contact", global: "Context and consent matter more across markets" },
  { criterion: "Digital infrastructure", local: "Helpful but not always central", global: "Required for continuity and discovery" },
  { criterion: "Governance", local: "Compact decision structure", global: "Central standards with regional authority" },
  { criterion: "Research potential", local: "Deep market-specific insight", global: "Cross-market comparison and shared themes" },
  { criterion: "Brand recognition", local: "High relevance in one market", global: "Broader identity with variable local awareness" },
  { criterion: "Member retention", local: "Supported by regular proximity", global: "Depends on useful local and cross-market value" },
  { criterion: "Operating cost", local: "Concentrated team and event costs", global: "Hosts, travel, systems and localization" },
  { criterion: "Expansion risk", local: "Limited geographic upside", global: "Fragmentation and inconsistent standards" },
];
comparisonPage.sections = [
  { heading: "The models are not mutually exclusive", body: "A strong global executive network often combines global reach with local depth. Members may identify with the wider network while building their strongest relationships through regional gatherings, functional peer groups and recurring smaller formats." },
  { heading: "Choose local when depth is the immediate priority", body: "A local model is often the right starting point when members share a market, can meet regularly and need strong contextual relevance. It lets the organizer learn how member fit, facilitation and cadence work before taking on expansion complexity." },
  { heading: "Choose global when cross-market value is real", body: "A global model is justified when members benefit from relationships, insight or opportunities across markets. International branding by itself is not enough. The operating system must help members find relevant people and knowledge beyond their home region." },
  { heading: "Use a connected regional model", body: "Many communities should use a connected regional model: one identity and trust standard, multiple local conveners, regional programs and a small number of shared global experiences. This gives members proximity without limiting the network to one market." },
  { heading: "Decision checklist", body: "Choose the simplest model that can fulfill the member promise.", points: ["Where is the member problem concentrated?", "How often must members meet to create value?", "Is cross-market diversity useful or merely impressive?", "Can the team support regional hosts and data practices?", "Which standards must remain global?", "Which formats should be locally adapted?"] },
];
comparisonPage.faq = [
  { question: "Is a global network better than a local community?", answer: "No. The better model is the one that fulfills a clear member need. Local communities can create greater relationship depth, while global networks can create wider perspective and cross-market value." },
  { question: "Can a local community become global?", answer: "Yes, but it should expand only after its member promise, selection standards and operating cadence are repeatable." },
  { question: "Can members belong globally but participate locally?", answer: "Yes. This connected regional model is often the most practical way to combine global identity with strong relationships." },
];

for (const [slug, override] of Object.entries(depth)) {
  const page = pages.find(item => item.slug === slug);
  if (page) Object.assign(page, override);
}
globalGuide.relatedTemplate = "community-host-briefing-template";
globalGuide.sources = [{label:"ICO data protection principles",url:"https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/data-protection-principles/a-guide-to-the-data-protection-principles/",note:"Primary guidance relevant to cross-border member data practices."}];
pages.push({
  slug:"sources-and-references",title:"Sources and References",category:"Project documentation",group:"Project",summary:"Primary references used for governance, research, confidentiality, privacy, consent, accessibility and disclosure.",intro:"The playbook cites external sources when they support a specific factual claim, rule or standard; sources are not added merely for decoration.",
  sections:[
    {heading:"Source selection policy",body:"Primary institutional sources are preferred for rules, standards and formal definitions. Public sources are assessed for authority, relevance and currency. Publisher operating experience and editorial judgment are labeled separately from external evidence."},
    {heading:"Confidentiality and the Chatham House Rule",body:"Chatham House defines its Rule and explains that it permits use of information while protecting the identity and affiliation of speakers and participants. The Rule is not legally binding and is different from a stricter off-the-record agreement."},
    {heading:"Privacy and data protection",body:"The UK Information Commissioner’s Office explains core data protection principles including lawfulness, purpose limitation, data minimisation, accuracy, retention, security and accountability. Community operators should obtain qualified guidance for obligations in their jurisdictions."},
    {heading:"Accessibility",body:"The World Wide Web Consortium publishes WCAG 2.2 as a Recommendation for making web content more accessible. This project uses semantic structure, visible focus states, responsive tables and reduced-motion support as practical implementation measures."},
    {heading:"Sponsorship disclosure",body:"The U.S. Federal Trade Commission’s Endorsement Guides explain that material connections affecting how people evaluate an endorsement should be disclosed. Operators should seek jurisdiction-specific advice for their own promotional activity."},
    {heading:"Association governance and conflicts",body:"ASAE’s association ethics guidance covers conduct and conflict-of-interest practices. Community and advisory formats should state decision rights, disclosure duties and how conflicts are managed."},
    {heading:"Advisory boards",body:"The UK government’s board-member conduct code provides a primary governance reference for duties and conflicts. An advisory board must also state clearly that its authority differs from a statutory or fiduciary board."},
    {heading:"Research ethics, surveys and consent",body:"AAPOR publishes survey-research best practices, the Belmont Report provides a foundational human-subject ethics framework, and the ICO explains valid consent. Community research should identify its sample, method and limits and should not treat event attendance as permission to quote or publish."}
  ],
  sources:[
    {label:"Chatham House Rule",url:"https://www.chathamhouse.org/about-us/chatham-house-rule",note:"Official definition and explanation."},
    {label:"ICO data protection principles",url:"https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/data-protection-principles/a-guide-to-the-data-protection-principles/",note:"Official organizational guidance."},
    {label:"WCAG 2.2",url:"https://www.w3.org/TR/WCAG22/",note:"W3C Recommendation."},
    {label:"FTC Endorsement Guides",url:"https://www.ftc.gov/news-events/topics/truth-advertising/advertisement-endorsements",note:"Official U.S. advertising guidance."},
    {label:"ASAE Ethics Toolkit for Associations",url:"https://www.asaecenter.org/-/media/models-and-samples/6/6/1/5/ASAE-Ethics-Toolkit-March-2025.ashx",note:"Primary association-sector ethics and conflicts guidance."},
    {label:"AAPOR Best Practices for Survey Research",url:"https://aapor.org/standards-and-ethics/best-practices/",note:"Primary professional survey-methodology guidance."},
    {label:"The Belmont Report",url:"https://www.hhs.gov/ohrp/regulations-and-policy/belmont-report/index.html",note:"Primary research-ethics framework."},
    {label:"ICO guidance on consent",url:"https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/lawful-basis/consent/",note:"Primary regulator guidance on consent."},
    {label:"Code of Conduct for Board Members of Public Bodies",url:"https://www.gov.uk/government/publications/code-of-conduct-for-board-members-of-public-bodies",note:"Primary governance and conflicts reference."}
  ]
});
for (const template of templates) {
  pages.push({slug:template.slug,title:template.title,category:"Template",group:"Templates",summary:`A complete, copy-ready ${template.title.toLowerCase()} with clear placeholders and adaptation notes.`,intro:`This template provides usable starting text for ${template.title.toLowerCase()}; adapt it to the community, format and jurisdiction.`,sections:[],template:{content:template.content,instructions:template.instructions,relatedGuide:template.relatedGuide}});
}
export const featured = pages.slice(0,4);
export const groups = [
  { number:"01", name:"Principles", id:"principles", description:"Norms that protect trust, contribution and audience quality." },
  { number:"02", name:"Global networks", id:"global", description:"Standards and local adaptation across markets." },
  { number:"03", name:"Role-based forums", id:"roles", description:"Different jobs create different needs, risks and agendas." },
  { number:"04", name:"Event formats", id:"formats", description:"Choose a room and format that serve the member problem." },
  { number:"05", name:"Governance", id:"governance", description:"Clear decision rights, sponsor boundaries and conduct." },
  { number:"06", name:"Comparisons", id:"comparisons", description:"Direct distinctions between adjacent community models." },
  { number:"07", name:"Measurement", id:"measurement", description:"Evidence of participation, relationships and member value." },
  { number:"08", name:"Project", id:"project", description:"Methodology, disclosure, citation and contribution." },
];
