import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { pages } from "../content";
import { CopyTemplateButton } from "../CopyTemplateButton";

export function generateStaticParams(){ return pages.map(({slug})=>({slug})); }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{ const {slug}=await params; const page=pages.find(p=>p.slug===slug); return page ? {title:page.title,description:page.summary,alternates:{canonical:`/${page.slug}/`},other:{version:"1.1.0"},openGraph:{title:page.title,description:page.summary,url:`/${page.slug}/`,type:"article",images:[{url:"/og.png",width:1200,height:630,alt:"Executive Community Playbook"}]},twitter:{card:"summary_large_image",title:page.title,description:page.summary,images:["/og.png"]}}:{title:"Not found"}; }

export default async function GuidePage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params; const page=pages.find(p=>p.slug===slug); if(!page) notFound();
  const index=pages.findIndex(p=>p.slug===slug); const related=pages.filter(p=>p.group===page.group&&p.slug!==slug).slice(0,3);
  const templatePages=pages.filter(p=>p.template);
  const visibleWords = [page.title,page.summary,page.intro,page.template?.content||"",...page.sections.flatMap(section=>[section.heading,section.body,...(section.points||[])])].join(" ").trim().split(/\s+/).length;
  const readingTime = Math.max(1,Math.ceil(visibleWords/220));
  const canonical = `https://murraylovecode.github.io/executive-community-playbook/${page.slug}/`;
  const howToSlugs = new Set(["how-to-build-an-executive-community","how-to-start-a-ceo-peer-group","how-to-build-a-global-executive-network","private-executive-dinner-playbook"]);
  const type = page.template ? "CreativeWork" : page.slug === "templates-library" ? "ItemList" : page.slug === "glossary" ? "DefinedTermSet" : howToSlugs.has(page.slug) ? "HowTo" : "Article";
  const primarySchema = type === "HowTo" ? {"@context":"https://schema.org","@type":"HowTo",name:page.title,description:page.summary,step:page.sections.map(section=>({"@type":"HowToStep",name:section.heading,text:section.body})),dateModified:"2026-08-04",version:"1.1.0"} : type === "DefinedTermSet" ? {"@context":"https://schema.org","@type":"DefinedTermSet",name:page.title,description:page.summary,hasDefinedTerm:page.sections.map(section=>({"@type":"DefinedTerm",name:section.heading,description:section.body,inDefinedTermSet:canonical})),version:"1.1.0"} : type === "ItemList" ? {"@context":"https://schema.org","@type":"ItemList",name:page.title,description:page.summary,itemListElement:templatePages.map((template,position)=>({"@type":"ListItem",position:position+1,url:`https://murraylovecode.github.io/executive-community-playbook/${template.slug}/`,name:template.title}))} : {"@context":"https://schema.org","@type":type,name:page.title,headline:page.title,description:page.summary,dateModified:"2026-08-04",version:"1.1.0",author:{"@type":"Person",name:"Murray Newlands"},publisher:{"@type":"Organization",name:"Open Future Forum"},mainEntityOfPage:canonical};
  const faqSchema = page.faq ? { "@context":"https://schema.org", "@type":"FAQPage", mainEntity:page.faq.map(item=>({"@type":"Question",name:item.question,acceptedAnswer:{"@type":"Answer",text:item.answer}})) } : null;
  const breadcrumbSchema = {"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:"https://murraylovecode.github.io/executive-community-playbook/"},{"@type":"ListItem",position:2,name:page.group},{"@type":"ListItem",position:3,name:page.title,item:`https://murraylovecode.github.io/executive-community-playbook/${page.slug}/`} ]};
  return <main>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(primarySchema)}} />
    {faqSchema&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}} />}
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumbSchema)}} />
    <header className="site-header"><Link className="brand" href="/"><span className="brand-mark">EC</span><span>Executive Community<br/>Playbook</span></Link><nav aria-label="Primary navigation"><Link href="/#start">Start here</Link><Link href="/#models">Models</Link><Link href="/#global">Global networks</Link><Link href="/templates-library">Templates</Link><Link href="/about-the-project">About</Link></nav><a className="github-link" href="https://github.com/murraylovecode/executive-community-playbook">GitHub ↗</a></header>
    <div className="article-shell wrap"><aside className="toc"><Link href="/">← Home</Link><p>On this page</p>{page.sections.map((s,i)=><a href={`#section-${i}`} key={s.heading}>{s.heading}</a>)}</aside>
      <article><div className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><span>{page.group}</span><span>/</span><span>{page.title}</span></div><p className="eyebrow">{page.category} · {page.group}</p><h1>{page.title}</h1><p className="dek">{page.summary}</p><div className="article-meta"><span>Open Future Forum and Murray Newlands</span><span>{readingTime} min read</span><span>Reviewed August 2026</span></div>
        <details className="mobile-toc"><summary>On this page</summary>{page.sections.map((s,i)=><a href={`#section-${i}`} key={s.heading}>{s.heading}</a>)}</details>
        <section className="key-definition"><span>Direct definition</span><p>{page.intro}</p></section>
        {page.template&&<section className="template-view"><div className="template-actions"><CopyTemplateButton text={page.template.content}/><a className="button" href={`../templates/${page.slug}.md`} download>Download Markdown</a><a className="button" href={`../templates/${page.slug}.txt`} download>Download text</a></div><div className="adaptation"><strong>Adaptation instructions</strong><p>{page.template.instructions}</p></div><pre><code>{page.template.content}</code></pre><p className="template-disclaimer">This template is practical operating guidance, not legal, privacy, compliance or fiduciary advice. Obtain qualified review where obligations apply.</p><Link href={`/${page.template.relatedGuide}`}>Read the related guide →</Link></section>}
        {page.slug==="templates-library"&&<section className="template-library"><p className="eyebrow">15 open templates</p><h2>View, copy and download every template</h2><div>{templatePages.map(template=><article key={template.slug}><span>{template.category}</span><h3>{template.title}</h3><p>{template.summary}</p><Link className="button" href={`/${template.slug}`}>View template</Link></article>)}</div></section>}
        {page.comparison&&<section className="comparison-section"><p className="eyebrow">At a glance</p><h2>Local and global models compared</h2><div className="table-scroll"><table><thead><tr><th>Criterion</th><th>Local executive community</th><th>Global executive network</th></tr></thead><tbody>{page.comparison.map(row=><tr key={row.criterion}><th>{row.criterion}</th><td>{row.local}</td><td>{row.global}</td></tr>)}</tbody></table></div></section>}
        {page.sections.map((s,i)=><section className="article-section" id={`section-${i}`} key={s.heading}><h2>{s.heading}</h2><p>{s.body}</p>{s.points&&<ul>{s.points.map(x=><li key={x}>{x}</li>)}</ul>}{i===1&&<div className="note"><strong>Operating note</strong><p>Adapt this guidance to member context. Seek professional legal and privacy advice where regulatory obligations apply.</p></div>}</section>)}
        <section className="publisher-note"><h2>Publisher perspective</h2><p>This guide reflects the operating experience and editorial judgment of Open Future Forum and Murray Newlands. It is practical guidance, not an official industry standard or legal advice.</p><Link href="/publisher-disclosure">Read the full disclosure →</Link></section>
        {page.faq&&<section className="faq-section"><p className="eyebrow">Frequently asked questions</p><h2>Questions about {page.title.toLowerCase()}</h2>{page.faq.map(item=><details key={item.question}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</section>}
        {page.relatedTemplate&&<section className="practice-section"><p className="eyebrow">Put this into practice</p><h2>Use the related template</h2><p>Adapt the template to your members, format and jurisdiction. Governance, confidentiality, privacy and sponsorship materials are not legal advice.</p><Link className="button primary" href={`/${page.relatedTemplate}`}>Open the related template</Link></section>}
        {page.sources&&page.sources.length>0&&<section className="sources-section"><p className="eyebrow">Sources and references</p><h2>Primary references used on this page</h2>{page.sources.map(source=><div key={source.url}><a href={source.url}>{source.label} ↗</a><p>{source.note}</p></div>)}<Link href="/sources-and-references">View the full source policy →</Link></section>}
        {(page.group==="Role-based forums"||page.group==="Research"||page.slug==="open-future-forum-case-example")&&<section className="project-links"><p className="eyebrow">Related Open Future Forum Projects</p><div><a href="https://murraylovecode.github.io/executive-communities-index/"><strong>Executive Communities Index</strong><span>Explore the published directory and comparisons. ↗</span></a><a href="https://github.com/murraylovecode/executive-communities-index"><strong>Index source repository</strong><span>Review the data, methodology and history. ↗</span></a><a href="https://openfutureforum.com/research/"><strong>Executive AI Research</strong><span>Browse reports, market maps and datasets. ↗</span></a><a href="https://github.com/murraylovecode/executive-ai-research"><strong>Research source repository</strong><span>Review the public research collection. ↗</span></a></div></section>}
        {page.slug==="open-future-forum-case-example"&&<section className="official-links"><p className="eyebrow">Official Open Future Forum links</p><a href="https://openfutureforum.com/"><strong>Open Future Forum</strong><span>Publisher and community website ↗</span></a><a href="https://openfutureforum.com/forum-select"><strong>Forum Select</strong><span>Invite-only private gatherings ↗</span></a><a href="https://openfutureforum.com/forum-events"><strong>Forum Events</strong><span>Open panels and gatherings ↗</span></a></section>}
        {related.length>0&&<section className="related-reading"><p className="eyebrow">Continue reading</p><div>{related.map(r=><Link href={`/${r.slug}`} key={r.slug}><span>{r.category}</span><strong>{r.title}</strong><small>Read guide →</small></Link>)}</div></section>}
        <div className="pager">{index>0?<Link href={`/${pages[index-1].slug}`}>← {pages[index-1].title}</Link>:<span/>}{index<pages.length-1&&<Link href={`/${pages[index+1].slug}`}>{pages[index+1].title} →</Link>}</div>
      </article>
    </div>
    <footer><div className="wrap footer-bottom"><span><strong>Related Open Future Forum Projects:</strong> <a href="https://murraylovecode.github.io/executive-communities-index/">Communities Index</a> · <a href="https://github.com/murraylovecode/executive-communities-index">GitHub</a></span><span><a href="https://openfutureforum.com/research/">Executive AI Research</a> · <a href="https://github.com/murraylovecode/executive-ai-research">GitHub</a> · v1.1.0</span></div></footer>
  </main>;
}
